name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes (UTC time)
  workflow_dispatch:        # Allow manual trigger too

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -L --fail http://scoliosisweb.online || echo "Ping failed"
